// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/case": {
            "get": {
                "description": "get case endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "get case endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update case endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "update case endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post case endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "post case endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete case endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "delete case endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/case/:id": {
            "get": {
                "description": "get case by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "case"
                ],
                "summary": "get case by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/definition": {
            "get": {
                "description": "get definition endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "definition"
                ],
                "summary": "get definition endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update definition endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "definition"
                ],
                "summary": "update definition endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post definition endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "definition"
                ],
                "summary": "post definition endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete definition endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "definition"
                ],
                "summary": "delete definition endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/definition/:id": {
            "get": {
                "description": "get definition by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "definition"
                ],
                "summary": "get definition by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "say hello",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hello"
                ],
                "summary": "hello endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/input-source": {
            "get": {
                "description": "get input-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "input-source"
                ],
                "summary": "get input-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update input-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "input-source"
                ],
                "summary": "update input-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post input-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "input-source"
                ],
                "summary": "post input-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete input-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "input-source"
                ],
                "summary": "delete input-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/input-source/:id": {
            "get": {
                "description": "get input-source by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "input-source"
                ],
                "summary": "get input-source by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/output-source": {
            "get": {
                "description": "get output-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "output-source"
                ],
                "summary": "get output-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update output-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "output-source"
                ],
                "summary": "update output-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post output-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "output-source"
                ],
                "summary": "post output-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete output-source endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "output-source"
                ],
                "summary": "delete output-source endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/output-source/:id": {
            "get": {
                "description": "get output-source by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "output-source"
                ],
                "summary": "get output-source by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/reply": {
            "get": {
                "description": "get reply endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "get reply endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update reply endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "update reply endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post reply endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "post reply endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete reply endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "delete reply endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/reply/:id": {
            "get": {
                "description": "get reply by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reply"
                ],
                "summary": "get reply by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/settings/setting": {
            "get": {
                "description": "get setting endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get setting endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update setting endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "update setting endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post setting endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "post setting endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete setting endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "delete setting endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/settings/setting/:id": {
            "get": {
                "description": "get setting by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get setting by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/transformer": {
            "get": {
                "description": "get transformer endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transformer"
                ],
                "summary": "get transformer endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update transformer endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transformer"
                ],
                "summary": "update transformer endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post transformer endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transformer"
                ],
                "summary": "post transformer endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete transformer endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transformer"
                ],
                "summary": "delete transformer endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/transformer/:id": {
            "get": {
                "description": "get transformer by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transformer"
                ],
                "summary": "get transformer by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/users/user": {
            "get": {
                "description": "get user endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "put": {
                "description": "update user endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update user endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "post": {
                "description": "post user endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "post user endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete user endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        },
        "/users/user/:id": {
            "get": {
                "description": "get user by id endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user by id endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "param"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
